'use strict';
const csrf=document.querySelector('meta[name="csrf-token"]').content;
const displayTime=t=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(t));
document.querySelectorAll('time[datetime]').forEach(el=>{el.textContent=displayTime(el.dateTime);el.title=el.dateTime+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone;});
async function action(url,body){const response=await fetch(url,{method:'POST',headers:{'x-csrf-token':csrf,'Content-Type':'application/json'},body:JSON.stringify(body||{})});const text=await response.text();let data;try{data=JSON.parse(text);}catch{throw new Error(text||'The request could not be completed.');}if(!response.ok)throw new Error(data.error||'The request could not be completed.');return data;}
const form=document.getElementById('schedule-form');
if(form){
 const upload=document.getElementById('upload-at'),publish=document.getElementById('publish-at'),zone=document.getElementById('timezone'),summary=document.getElementById('time-summary');
 zone.options[0].textContent='Local · '+Intl.DateTimeFormat().resolvedOptions().timeZone+' (automatic daylight saving)';
 function timestamp(value){if(!value)return '';const d=new Date(zone.value==='local'?value:value+':00'+zone.value);if(!Number.isFinite(d.getTime()))throw new Error('Choose a valid date and time.');if(zone.value==='local'){const parts=value.split(/[-T:]/).map(Number);if(d.getHours()!==parts[3]||d.getMinutes()!==parts[4])throw new Error('This local time does not exist during the daylight-saving change. Choose another time or an explicit offset.');}return d.toISOString();}
 function updateSummary(){try{summary.textContent=publish.value?'Publication: '+timestamp(publish.value)+' · UTC. Leave time for upload and processing.':'All dates are saved as UTC. Leave time for uploading and processing.';}catch(e){summary.textContent=e.message;}}
 [publish,upload,zone].forEach(el=>el.addEventListener('change',updateSummary));
 let objectURL;const preview=document.getElementById('local-preview');document.getElementById('video').addEventListener('change',e=>{if(objectURL)URL.revokeObjectURL(objectURL);const f=e.target.files[0];preview.hidden=!f;if(f){objectURL=URL.createObjectURL(f);preview.src=objectURL;}});
 form.addEventListener('submit',e=>{e.preventDefault();const error=document.getElementById('form-error'),button=form.querySelector('button[type=submit]'),status=document.getElementById('transfer-status');error.hidden=true;try{const data=new FormData(form);data.set('upload_at',timestamp(upload.value));data.set('publish_at',timestamp(publish.value));data.set('synthetic_media',document.getElementById('synthetic').checked?'true':'false');if(new Date(data.get('publish_at')).getTime()<=Math.max(Date.now(),data.get('upload_at')?new Date(data.get('upload_at')).getTime():Date.now())+60000)throw new Error('Publication must be over 60 seconds after now and the upload time.');button.disabled=true;status.textContent='Transferring video to this server…';const xhr=new XMLHttpRequest();xhr.open('POST','/api/jobs');xhr.setRequestHeader('x-csrf-token',csrf);xhr.upload.onprogress=e=>{if(e.lengthComputable)status.textContent='Transferring to server · '+Math.round(e.loaded/e.total*100)+'%';};const fail=message=>{error.textContent=message;error.hidden=false;button.disabled=false;status.textContent='';error.scrollIntoView({block:'center'});};xhr.onerror=()=>fail('Connection lost. Check the queue before submitting again.');xhr.onload=()=>{let result;try{result=JSON.parse(xhr.responseText);}catch{return fail('The server could not accept this upload. Check the queue before submitting again.');}if(xhr.status>=200&&xhr.status<300){location.href='/jobs/'+result.id;}else fail(result.error||'Upload could not be saved.');};xhr.send(data);}catch(e){error.textContent=e.message;error.hidden=false;}});
}
document.querySelectorAll('[data-cancel]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Cancel this queued video?'))return;button.disabled=true;try{await action('/api/jobs/'+button.dataset.cancel+'/cancel');location.reload();}catch(e){document.getElementById('action-status').textContent=e.message;button.disabled=false;}}));
document.querySelectorAll('.retry-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await action('/api/jobs/'+form.dataset.job+'/retry',{publish_at:new Date(form.querySelector('input').value).toISOString()});location.reload();}catch(e){document.getElementById('action-status').textContent=e.message;button.disabled=false;}}));
// Refresh only when no editable form is present, so uploads and user input are never interrupted.
if(!document.querySelector('form')){let signature;setInterval(async()=>{if(document.hidden)return;try{const r=await fetch('/api/jobs');if(!r.ok)return;const jobs=await r.json();const current=JSON.stringify(jobs.map(j=>[j.id,j.state,j.bytes_sent,j.updated_at]));if(signature&&signature!==current)location.reload();signature=current;}catch{/* Next poll recovers a temporary disconnection. */}},5000);}
